# Generated by Django 5.0.1 on 2024-01-23 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=300)),
                ('Doctor_Name', models.CharField(max_length=300)),
                ('Patient_id', models.IntegerField()),
                ('Patient_Data', models.FileField(upload_to='')),
                ('Admit_date', models.DateField(default=django.utils.timezone.now)),
                ('Discharge_date', models.DateField(null=True)),
            ],
        ),
    ]
